name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master


defaults:
  run:
    working-directory: ./infrastructure-code
jobs: 
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Hexo CLI and Deployer S3
      run: |
        npm install hexo-cli
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v1 
      with: 
        aws-access-key-id: ${{ secrets.CDK_DEPLOYER_AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.CDK_DEPLOYER_AWS_SECRET_ACCESS_KEY }} 
        aws-region: ${{ secrets.AWS_REGION }} 
    - name: cdk diff 
      run: | 
        cdk diff --context domain=flo-in-dk.com --context subdomain=www 



